[env:esp32s3-idf]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.psram_type = opi
board_build.arduino.memory_type = qio_opi
board_build.partitions = partitions.csv
monitor_speed = 115200
build_flags =
    -DBOARD_HAS_PSRAM
    -DAPP_USB_VID=0x0D28
    -DAPP_USB_PID=0x0204
